import type { Metadata } from "next";
import { Jost, Cormorant } from "next/font/google";
import "./globals.css";
import clsx from "clsx";


const cormorant = Cormorant({
	subsets: ['latin'],
  variable: '--font-cormorant',
	display: 'swap',
})

const jost = Jost({
	subsets: ['latin'],
  variable: '--font-jost',
	display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${jost.variable} ${cormorant.variable}`}>
      <body >{children}</body>
    </html>
  );
}
